// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jatyzolstxhqiywofqmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphdHl6b2xzdHhocWl5d29mcW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDI4MDUsImV4cCI6MjA2NzI3ODgwNX0.BK63oXzyRouzZZ6RG2yb8cVGdsQz-dwoh7XLtjGDKHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});